flowchart LR

subgraph 0["src"]
subgraph 1["app"]
subgraph 2["(chat)"]
subgraph 3["components"]
4["Chat.tsx"]
7["ParameterInput.tsx"]
end
5["page.module.css"]
6["prompts.json"]
8["page.tsx"]
end
9["layout.tsx"]
A["globals.css"]
end
subgraph B["contexts"]
subgraph C["course-mode"]
subgraph D["application"]
subgraph E["ports"]
subgraph F["in"]
G["start-course-conversation.ts"]
end
subgraph V["out"]
W["course-repo.ts"]
end
end
subgraph X["use-cases"]
Y["start-course-conversation-concrete.test.ts"]
17["start-course-conversation-concrete.ts"]
end
end
subgraph P["entities"]
Q["course.ts"]
T["learning-roadmap.ts"]
U["learning-checkpoint.ts"]
end
subgraph 14["infra"]
subgraph 15["repo"]
16["in-memory-course-repo.ts"]
end
end
subgraph 18["interface"]
subgraph 19["controllers"]
1A["course-mode-controller.ts"]
end
subgraph 1B["web"]
subgraph 1C["react"]
1D["some-ui.tsx"]
end
end
end
end
end
subgraph H["shared"]
subgraph I["application"]
subgraph J["ports"]
subgraph K["out"]
L["id-provider.ts"]
M["llm-provider.ts"]
end
end
end
subgraph N["entities"]
O["llm-conversation.ts"]
R["project.ts"]
S["material.ts"]
1E["user.ts"]
end
subgraph Z["infra"]
subgraph 10["id"]
11["uuid-provider.ts"]
end
subgraph 12["llms"]
13["mock-llm-provider.ts"]
end
end
end
end
4-->5
4-->6
4-->7
7-->5
8-->4
8-->5
9-->A
G-->L
G-->M
G-->O
G-->Q
G-->W
O-->M
Q-->O
Q-->R
Q-->T
R-->S
T-->U
W-->Q
Y-->R
Y-->11
Y-->13
Y-->Q
Y-->T
Y-->16
Y-->17
11-->L
13-->M
16-->W
16-->Q
17-->L
17-->M
17-->O
17-->S
17-->Q
17-->U
17-->G
17-->W
1A-->L
1A-->M
1A-->G
1A-->W
1A-->Q
1D-->Q
1D-->1A
